# Generated by Django 2.1.2 on 2020-03-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='from_user',
            field=models.CharField(default='', max_length=500),
        ),
    ]
